---

- name: restart ntpd
  service: name=ntpd state=restarted
  sudo: yes

- name: restart firewalld
  service: name=firewalld state=restarted
  sudo: yes

- name: systemctl daemon-reload
  command: systemctl daemon-reload
  sudo: yes