---

- yum: name=tigervnc-server

- copy: src=vncserver.service dest=/etc/systemd/system/vncserver@:4.service mode=0644
  notify: systemctl daemon-reload

- service: name=vncserver@:4.service state=started enabled=yes

- firewalld: port=5094/tcp state=enabled permanent=true
  notify: restart firewalld